config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :astrologists, only: [:index, :show, :new, :create, :edit, :update, :dashboard] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [] do
    member do
      patch '/cancel', to: 'bookings#cancel'
    end
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:show]
  get 'dashboard', to: 'astrologists#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astrologist.rb
class Astrologist < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo

  validates :experience, presence: true
  validates :price, presence: true
  validates :speciality, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:speciality],
    associated_against: {
      user: [:first_name, :last_name]
    },
    using: {
      tsearch: { prefix: true }
    }

  def rating_average
    return 0 if reviews.empty?

    ratings = reviews.pluck(:rating)
    return (ratings.sum / ratings.length)
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :astrologist
  has_many :reviews
  validates :date, presence: true
  validates :time, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true, inclusion: 1..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :astrologists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_date, presence: true
  validates :birth_time, presence: true
  validates :birth_place, presence: true
  validates :photo, presence: true

  def astrologist?
    astrologists.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date, :birth_time, :birth_place, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birth_date, :birth_time, :birth_place, :photo])
  end
end

app/controllers/astrologists_controller.rb
class AstrologistsController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = " \
        astrologists.speciality ILIKE :query \
        OR users.first_name ILIKE :query \
        OR users.last_name ILIKE :query \
      "
      @astrologists = Astrologist.joins(:user).where(sql_query, query: "%#{params[:query]}%").sort_by {|astrologist| astrologist.rating_average }.reverse
    else
      @astrologists = Astrologist.all.sort_by {|astrologist| astrologist.rating_average }.reverse
    end
  end

  def show
    @booking = Booking.new
    @unavailable_dates = @astrologist.bookings.map do |booking|
      booking.date
    end
  end

  def dashboard
    @astrologist = Astrologist.find_by(user: current_user)
  end

  def new
    @astrologist = Astrologist.new
  end

  def create
    @astrologist = Astrologist.new(strong_params)
    @astrologist.user = current_user
    if @astrologist.save
      redirect_to astrologist_path(@astrologist)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @astrologist.update(strong_params)
    redirect_to astrologist_path(@astrologist)
  end

  private

  def set_params
    @astrologist = Astrologist.find(params[:id])
  end

  def strong_params
    params.require(:astrologist).permit(:experience, :price, :user_id, speciality: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  end

  def create
    @booking = Booking.new(booking_params)
    @astrologist = Astrologist.find(params[:astrologist_id])
    @booking.user = current_user
    @booking.astrologist = @astrologist

    if @booking.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def cancel
    # @user = User.find(current_user)
    @booking = Booking.find(params[:id])
    @booking.confirmed = false
    @booking.save

    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @review = Review.first
    @reviews = Review.all[1..-1]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to astrologist_path(@booking.astrologist)
    else render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/astrologists/dashboard.html.erb
<div class="container content">
  <div class="dashboard-center">
  <div class="profile-card-dash mt-5 mb-4 mr-5">
        <div class="card-top" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url('<%= cl_image_path current_user.photo.key %>')">
          <div class="name-card">
            <h1><%= current_user.first_name %></h1>
            <h1 class="horizontal-line pb-3"><%= current_user.last_name %></h1>
          </div>
        </div>
        <div class="card-bottom">
          <p> <strong>Date of birth:</strong> <%= current_user.birth_date.strftime(" %A %e %B %Y") %></p>
          <p> <strong>Number of Bookings:</strong> <%= @astrologist.bookings.count %></p>
          <p> <strong>Number of Reviews:</strong> <%= @astrologist.reviews.count %></p>
          <p> <strong>Average of my Ratings:</strong> <%@astrologist.rating_average.times do%>
              <i class="fas fa-star"></i>
            <% end %>
          </p>
        </div>
       </div>
       </div>
       <div class="text-center">
        <%= link_to 'Show my astrologist profile', astrologist_path(current_user.astrologists.first), class: "button my-3 mr-4" %>
        <%= link_to 'Edit astrologist profile', edit_astrologist_path(current_user.astrologists.first), class: "button my-3 mr-4" %>
      </div>

    <div class="reviews text-center my-5">
    <h2>My Bookings</h2>
      <div class="row">
        <% @astrologist.bookings.sort.reverse.each do |booking| %>
          <div class="col-6">
            <div class="box-rating">
              <div class="d-flex justify-content-between align-items-centermx-3">
                <div class="d-flex">
                  <%= cl_image_tag booking.user.photo.key, class: "avatar-large" %>
                  <div class="text-left ml-3">
                    <p class="mb-0"><strong>Name:</strong> <%= booking.user.first_name %> <%= booking.user.last_name %></p>
                    <p class="mb-0"><strong>Booking date:</strong> <%= booking.date.strftime(" %A %e %B %Y") %> <%= booking.time.strftime(" %l %p %M") %></p>
                    <p class="mb-0"><strong>Birth date of client:</strong> <%= booking.user.birth_date.strftime(" %A %e %B %Y") %> <%= booking.user.birth_time.strftime(" %l %p %M") %></p>
                    <p class="mb-0"><strong>Birth place of client:</strong> <%= booking.user.birth_place %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>

    <div class="reviews text-center my-5">
    <h2>My Reviews</h2>
      <div class="row">
        <% @astrologist.reviews.sort.reverse.each do |review| %>
          <div class="col-6">
            <div class="box-rating">
              <div class="d-flex justify-content-between align-items-centermx-3">
                <div class="d-flex">
                  <%= cl_image_tag review.booking.user.photo.key, class: "avatar-large" %>
                  <div class="text-left ml-3">
                    <p class="mb-0"><%= review.booking.user.first_name %></p>
                    <p id="date-booking"><%= review.booking.date.strftime("%B %Y") %></p>
                  </div>
                </div>
                <p>
                  <% review.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                </p>
              </div>
              <p class="mt-3 pl-3 text-left"><%= review.comment%></p>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>
</div>

app/views/astrologists/edit.html.erb
<div class="content text-center mt-5">
  <h1>Edit profile</h1>
  <div class="container d-flex justify-content-center py-5 my-3">
  <%= simple_form_for(@astrologist) do |f| %>
      <%= f.input :experience, :label_html => { :class => 'label' } %>
      <%= f.input :price, :label_html => { :class => 'label' } %>
      <%= f.submit "Edit profile", class: "button submit" %>
  <% end %>
  </div>
</div>

app/views/astrologists/index.html.erb
<div class="container content">

  <div class="astrologists-list">
    <h1 class=" title pt-5">Our amazing astrologists are here to help you</h1>
      <div class="grid">
        <% @astrologists.each do |astrologist| %>
        <%= link_to astrologist_path(astrologist) do %>
          <div class="d-flex justify-content-center">
            <div class="astrologist-card my-4">
              <div class="card-top" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url('<%= cl_image_path astrologist.user.photo.key %>')">
                <div class="name-card">
                  <h1><%= astrologist.user.first_name %></h1>
                  <h1 class="horizontal-line"><%= astrologist.user.last_name %></h1>
                </div>
              </div>
              <div class="card-bottom p-3 d-flex justify-content-between">
                <p> <strong><%= astrologist.price %></strong> € / hour</p>
                <p><%astrologist.rating_average.times do%>
                    <i class="fas fa-star"></i>
                    <% end %>
                </p>
              </div>
              <ul class="list-group list-group-horizontal justify-items-center">
                <% astrologist.speciality.gsub(/[^a-zA-Z,]/i, '').split(',').each do |speciality| %>
                  <li class="list-group-item"><%= speciality %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/astrologists/new.html.erb
<div class="content">
  <div class="container d-flex justify-content-center py-5 my-3">
    <%= simple_form_for @astrologist do |f| %>
      <%= f.input :experience, :label => 'Tell us about your experience:', :label_html => { :class => 'label' } %>
      <%= f.input :price, :label => 'Price per hour:', :label_html => { :class => 'label' } %>
      <%= f.input :speciality, :label => 'Speciality', collection: %w[readings horoscope coaching compatibility], input_html: { multiple: true }, include_hidden: false, as: :check_boxes %>
      <%= f.submit 'Create astrologist profile', class:'button submit' %>
    <% end %>
  </div>
</div>

app/views/astrologists/show.html.erb
<div class="container content">

  <div class="d-flex align-items-center mt-5">

    <div id="l-box-shadow" class="mr-5">
      <% if @astrologist.user.photo.attached? %>
        <%= cl_image_tag @astrologist.user.photo.key, width: 350, heigth: 500 %>
      <% end %>
    </div>

    <div class="astro-info">
      <h1 class="text-center pb-3"><%= @astrologist.user.first_name %> <%= @astrologist.user.last_name %></h1>
      <ul class="list-group list-group-horizontal justify-items-center">
        <% @astrologist.speciality.gsub(/[^a-zA-Z,]/i, '').split(',').each do |speciality| %>
        <li class="list-group-item"><%= speciality %></li>
        <% end %>
      </ul>
      <div class="d-flex" style="align-items: baseline;">
        <h4 class="pt-5"> Price: <%= @astrologist.price %>€/hour</h4>
        <% if user_signed_in? && current_user.id == @astrologist.user_id %>
            <%= link_to edit_astrologist_path(@astrologist) do %>
              <i class="far fa-edit edit-link pl-4"></i>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mt-5 pink-line"></div>


  <div class="d-flex justify-items-center mt-5  justify-content-between">
    <div class="astro-exp ml-4 mr-3">
      <h3 class="text-center">Experience:</h3>
      <p class="text-left mt-4"><%= @astrologist.experience%></p>
    </div>

    <div class="appointment">


        <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
          <%= simple_form_for [@astrologist, @booking], method: "post" do |f| %>
            <%= f.input :date,
              as: :string,
              label: false,
              required: false,
              input_html: {class: "datepicker d-none", data: {unavailable_dates: @unavailable_dates.to_json}}
            %>
            <% if !user_signed_in? || current_user.id != @astrologist.user_id%>
              <%= f.input :time, :label => 'Appointment time:', :label_html => { :class => 'time-label' } %>
              <%= f.submit "Book this Astrologist", class: "button mt-3 btn-book" %>
            <% end %>
          <% end %>
        </div>
      </div>

  </div>
  <div class="mt-5 pink-line"></div>


  <div class="reviews text-center my-5">
    <h2><%=@astrologist.user.first_name%>'s Reviews</h2>
      <div class="row">
        <% @astrologist.reviews.sort.reverse.each do |review| %>
          <div class="col-6">
            <div class="box-rating">
              <div class="d-flex justify-content-between align-items-centermx-3">
                <div class="d-flex">
                  <%= cl_image_tag review.booking.user.photo.key, class: "avatar-large" %>
                  <div class="text-left ml-3">
                    <p class="mb-0"><%= review.booking.user.first_name %></p>
                    <p id="date-booking"><%= review.booking.date.strftime("%B %Y") %></p>
                  </div>
                </div>
                <p>
                  <% review.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                </p>
              </div>
              <p class="mt-3 pl-3 text-left"><%= review.comment%></p>
            </div>
          </div>
        <% end %>
      </div>
  </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="content">
  <h1 class="text-center mt-5">Book a session</h1>
  <div class="container d-flex justify-content-center py-5 my-3">
    <%= simple_form_for [@astrologist, @booking] do |f| %>
        <%= f.input :date, :label_html => { :class => 'label' } %>
        <%= f.input :time, :label_html => { :class => 'label' } %>
        <%= f.button :submit, "Book the Date", class:'button submit' %>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🪐Astromeet 🪐</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>


    <%= render 'shared/navbar' %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( https://www.wellandgood.com/wp-content/uploads/2020/01/01-13-Moon-Phases-Feature.jpg);">
    <div class="container">

      <h1 class="text-home">Find your best self with Astromeet...</h1>
      <div class="d-flex justify-content-center">
        <%= link_to "Meet our astrologists", astrologists_path, class: "button button-banner"  %>
      </div>
    </div>
  </div>
</div>

<div class="container content mt-5">
  <div class="services-info">
      <h1 class="pt-5 pb-3 text-center">What do you fancy?</h1>
        <div class="inline mt-5">
          <div class="service-card">
            <div class="icon"><%= image_tag"noun_coaching.png", alt: "chart reading", width: 60, height: 50 %>
            </div>
            <p>Love coaching</p>
          </div>
          <div class="service-card">
            <div class="icon"><%= image_tag"noun_chart_reading.png", alt: "chart reading", width: 60, height: 50 %>
            </div>
            <p>Natal chart reading</p>
          </div>
          <div class="service-card">
            <div class="icon"><%= image_tag"noun_compatibility.png", alt: "chart reading", width: 60, height: 50 %>
            </div>
            <p>Couple compatibility analysis</p>
          </div>
            <div class="service-card">
            <div class="icon"><%= image_tag"noun_12_forecast.png", alt: "chart reading", width: 60, height: 50 %>

            </div>
            <p>12-month astrology forecast</p>
            </div>
        </div>
    </div>

  <h1 class="text-center my-5">Our Top Reviews</h1>
 <div id="carouselExampleIndicators" class="carousel slide p-3 mt-4" data-ride="carousel" data-interval="3000">

  <div class="carousel-inner">
    <div class="carousel-item active text-center">
          <%= cl_image_tag @review.booking.user.photo.key, :style => "width: 80px;height: 80px;border-radius: 50%;object-fit: cover;"  %>
          <p><i class="fa fa-quote-left" aria-hidden="true"></i> <%= @review.comment  %> <i class="fa fa-quote-right" aria-hidden="true"></i></p>
          <p> <% @review.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
          </p>
          <p>Comment By: <%= @review.booking.user.first_name %></p>
          <p>About: <%= @review.booking.astrologist.user.first_name %> <%= @review.booking.astrologist.user.last_name %></p>
        </div>

        <% @reviews.each do |review|  %>

              <div class="carousel-item text-center">
            <%= cl_image_tag review.booking.user.photo.key, :style => "width: 80px;height: 80px;border-radius: 50%;object-fit: cover;"  %>
            <p><i class="fa fa-quote-left" aria-hidden="true"></i> <%= review.comment  %> <i class="fa fa-quote-right" aria-hidden="true"></i></p>
            <p> <% review.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
            </p>
            <p>Comment By: <%= review.booking.user.first_name %></p>
            <p> About: <%= review.booking.astrologist.user.first_name %> <%= review.booking.astrologist.user.last_name %></p>
          </div>
        <% end %>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only" >Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>
</div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand", data: {turbolinks: false} do %>
      <%= image_tag"logo_astromeet_bold.png", alt: "logo astromeet" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  <div>

  <div class="search-bar">
    <%= form_tag astrologists_path, method: :get do %>
      <div class="d-flex">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control", id: "search",
          placeholder: "Find an astrologist"
        %>
        <%= submit_tag "Search", id: "button-search" %>
      </div>
    <% end %>
  </div>


  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <%= link_to "Our Astrologists", astrologists_path, class: "text-right", id:"link-astro"  %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown" style="hover: #B98879 ">
        <%  if user_signed_in? %>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "logo_astromeet_bold.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user.astrologist?%>
            <%= link_to "Profile", dashboard_path, class: "dropdown-item"%>
          <% else %>
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item"%>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete,  class: "dropdown-item" %>
        <% else %>
          <%= link_to "Sign up/Log in", new_user_session_path, class: "dropdown-item", id:"link-astro"%>
        <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container content text-center">
  <div class="d-flex justify-content-center">
    <div class="left-div text-left">
      <div class="profile-card mt-5 mb-4 mr-5">
        <div class="card-top" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url('<%= cl_image_path @user.photo.key %>')">
          <div class="name-card">
            <h1><%= @user.first_name %></h1>
            <h1 class="horizontal-line pb-3"><%= @user.last_name %></h1>
          </div>
        </div>
        <div class="card-bottom">
          <p> <strong>Date of birth:</strong> <%= @user.birth_date.strftime(" %A %e %B %Y") %></p>
          <p> <strong>Time of birth:</strong> <%= @user.birth_time.strftime(" %l %p %M") %></p>
          <p> <strong>Place of birth:</strong> <%= @user.birth_place %></p>
          <p class="text-right">
            <%= link_to edit_user_registration_path do %>
                <i class="far fa-edit edit-link pl-4"></i>
              <% end %>
          </p>
        </div>
       </div>
       <div class="text-center">
          <% if current_user.astrologists.length <= 0 %>
            <%= link_to 'Become an astrologist', new_astrologist_path, class: "button my-3 mr-4" %>
          <% else %>
            <%= link_to 'Edit astrologist profile', edit_astrologist_path(current_user.astrologists.first), class: "button my-3 mr-4" %>
        <% end %>
      </div>
    </div>
    <div class="right-div d-flex flex-column ">
        <h1 class="text-center my-5 ml-5 booking-text">My Bookings</h1>
        <% current_user.bookings.order(date: :desc).each do |booking| %>
          <% if booking.confirmed == true  %>
            <div class="booking-card my-3 ml-5 mb-3">
              <div class="card-bottom text-left">
                <%= link_to cancel_booking_path(booking),
                 method: :patch,
                 remote: true,
                 data: { confirm: "Are you sure you want to cancel this appointment?" }  do %>
                 <i class="far fa-trash-alt cancel-appointment"></i>
                 <% end %>
                <p><strong>Astrologist:</strong> <%= booking.astrologist.user.first_name %> <%= booking.astrologist.user.last_name %></p>
                <p><strong>Appointment:</strong> <%= booking.date.strftime(" %A %e %B %Y") %> at <%= booking.time.strftime(" %l %p %M") %></p>
                <% if booking.date <= DateTime.now %>
                  <p>
                    <a class="button review-button" data-toggle="collapse" href="#collapse<%= booking.id %>" role="button" aria-expanded="false" aria-controls="collapseExample" id="review-button<%= booking.id %>">
                      Leave a review
                    </a>
                  </p>
                  <div class="collapse" id="collapse<%= booking.id %>">
                    <%= simple_form_for([booking,@review]) do |f| %>
                      <%= f.input :rating, as: :select, collection: 1..5 %>
                      <%= f.input :comment, placeholder: "It was a great session. I can already see myself changing!" %>
                    <div class="d-flex">
                      <%= f.submit "Leave a review", class: "button" %>
                    <% end %>
                    <a id="cancel-button" data-booking-id="<%= booking.id %>">Cancel</a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="booking-card my-5 ml-5 mb-3 card-cancelled">
              <div class="card-bottom text-left">
                <p class="txt-cancelled">CANCELLED</p>
                <p><strong>Astrologist:</strong> <%= booking.astrologist.user.first_name %> <%= booking.astrologist.user.last_name %></p>
                <p><strong>Appointment:</strong> <%= booking.date.strftime(" %A %e %B %Y") %> at <%= booking.time.strftime(" %l %p %M") %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
   </div>